version: "3.9"

services:
  nextapp:
    container_name: next-gamerps-dev
    image: next-game-dev
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
  

  db:
    container_name: next-game-db
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-postgres-dev:/var/lib/postgres/data

volumes:
  db-postgres-dev:
